org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft and NeoForge versions
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.67
neo_version_range=[26.2.0.67,26.3)

# Mod coordinates and metadata
mod_id=smart_particles
mod_name=Smart Particles
mod_license=MIT
mod_version=26.2.11
mod_group_id=com.chedidandrew
mod_authors=Andrew-Chedid
mod_description=A client-side performance mod that intelligently limits and culls particles.
